### PR TITLE
Disable indention where AS 3.0.1 and 3.1 disagree

### LINKED ISSUE #29464: Compiling with Astyle 3.1 - Errors
**Describe the bug**  
I tried to compile with linux and Astyle 3.1-1
```

$ make -j4 CLANG=1 CCACHE=1 NATIVE=linux64 RELEASE=1 TILES=1 
astyle -V: Artistic Style Version 3.1
#define VERSION "0.D"
CCACHE_CPP2=1 ccache clang++ -ffast-math -Os -Wall -Wextra -fsigned-char -Werror -std=c++11 -MMD -MP -m64 -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -Itools/format -Isrc tools/format/format.cpp src/json.cpp -o tools/format/json_formatter.cgi
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DTILES -DBACKTRACE -DLOCALIZE -ffast-math -Os -Wall -Wextra -fsigned-char -Werror -std=c++11 -MMD -MP -m64 -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -c src/action.cpp -o obj/tiles/action.o
astyle regressions found.
Formatted  src/game.cpp
make: *** [Makefile:994: astyle-check] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/action.cpp:23:
In file included from src/vehicle.h:13:
src/clzones.h:244:23: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( zone_manager && ) = default;
                      ^
src/clzones.h:220:19: note: move assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type 'const int'
        const int MAX_DISTANCE = 10;
                  ^
src/clzones.h:245:23: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( const zone_manager & ) = default;
                      ^
src/clzones.h:220:19: note: copy assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type 'const int'
        const int MAX_DISTANCE = 10;
                  ^
2 errors generated.
make: *** [Makefile:768: obj/tiles/action.o] Error 1
or 1

```
I always try to give detailed reports but here I don't know whats needed or helpful...

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: None```

#### Purpose of change
Make both Astyle 3.0.1 and 3.1 happy with the codebase.
Fixes #29464 

#### Describe the solution
The versions disagree about this chunk, so just tell them to ignore it.

### CODE REVIEW

**Comment by AMurkin** [comment]
Astyling it with 3.0.1 gives:
```cpp
            // *INDENT-OFF*
            const point offset {
                POSX - u.posx() + u.view_offset.x,
                POSY - u.posy() + u.view_offset.y
        };
            // *INDENT-ON*
```

**Comment by AMurkin** [comment]
This works though:
```cpp
            // *INDENT-OFF*
            const point offset {
                POSX - u.posx() + u.view_offset.x,
                POSY - u.posy() + u.view_offset.y
            }; // *INDENT-ON*
```

**Comment by kevingranade** [comment]
What the heck astyle

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by AMurkin** [comment]
Now it doesn't like another line.

```diff
diff --git a/src/game.cpp b/src/game.cpp
index 9f474c468c..d56e450083 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -3186,10 +3186,11 @@ void game::debug()

         case 24: {
 #if defined(TILES)
+            // *INDENT-OFF*
             const point offset {
                 POSX - u.posx() + u.view_offset.x,
-                     POSY - u.posy() + u.view_offset.y
-            };
+                POSY - u.posy() + u.view_offset.y
+            }; // *INDENT-ON*
             draw_ter();
             auto sounds_to_draw = sounds::get_monster_sounds();
             for( const auto &sound : sounds_to_draw.first ) {
@@ -3202,7 +3203,7 @@ void game::debug()
             draw_panels();
             inp_mngr.wait_for_any_key();
 #else
-            popup( _( "This binary was not compiled with tiles support." ) );
+                popup( _( "This binary was not compiled with tiles support." ) );
 #endif
         }
         break;
```

**Comment by AMurkin** [comment]
It's much worse for astyle 3.0.1 now.
