### ISSUE TITLE
Cannot compile in Ubuntu 16.04 with g++

### ISSUE THREAD

**Issue by xia-st** [CleverRaven/Cataclysm-DDA#19267]
My g++ version is  5.4.0 20160609, and the error message is below:

g++  -DGIT_VERSION -DLOCALIZE -ffast-math -Og -Wall -Wextra -g -D_GLIBCXX_DEBUG  -fsigned-char -std=c++11 -MMD -D_GNU_SOURCE -I/usr/include/ncursesw -c src/inventory_ui.cpp -o obj/inventory_ui.o
src/inventory_ui.cpp: In member function ‘std::__debug::vector<std::__cxx11::basic_string<char> > inventory_selector::get_stats() const’:
src/inventory_ui.cpp:1027:46: error: call to non-constexpr function ‘constexpr std::__debug::array<_Tp, _Nm>::size_type std::__debug::array<_Tp, _Nm>::size() const [with _Tp = std::__debug::array<std::__cxx11::basic_string<char>, 4ul>; long unsigned int _Nm = 2ul; std::__debug::array<_Tp, _Nm>::size_type = long unsigned int]’
     std::array<std::ostringstream, stats.size()> lines;
                                              ^
In file included from /usr/include/c++/5/array:338:0,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/functional:55,
                 from /usr/include/c++/5/memory:79,
                 from src/inventory_ui.h:5,
                 from src/inventory_ui.cpp:1:
/usr/include/c++/5/debug/array:140:7: note: ‘constexpr std::__debug::array<_Tp, _Nm>::size_type std::__debug::array<_Tp, _Nm>::size() const [with _Tp = std::__debug::array<std::__cxx11::basic_string<char>, 4ul>; long unsigned int _Nm = 2ul; std::__debug::array<_Tp, _Nm>::size_type = long unsigned int]’ is not usable as a constexpr function because:
       size() const noexcept { return _Nm; }
       ^
/usr/include/c++/5/debug/array:140:7: error: enclosing class of constexpr non-static member function ‘constexpr std::__debug::array<_Tp, _Nm>::size_type std::__debug::array<_Tp, _Nm>::size() const [with _Tp = std::__debug::array<std::__cxx11::basic_string<char>, 4ul>; long unsigned int _Nm = 2ul; std::__debug::array<_Tp, _Nm>::size_type = long unsigned int]’ is not a literal type
/usr/include/c++/5/debug/array:41:12: note: ‘std::__debug::array<std::__debug::array<std::__cxx11::basic_string<char>, 4ul>, 2ul>’ is not literal because:
     struct array
            ^
/usr/include/c++/5/debug/array:41:12: note:   ‘std::__debug::array<std::__debug::array<std::__cxx11::basic_string<char>, 4ul>, 2ul>’ has a non-trivial destructor
src/inventory_ui.cpp:1027:46: error: call to non-constexpr function ‘constexpr std::__debug::array<_Tp, _Nm>::size_type std::__debug::array<_Tp, _Nm>::size() const [with _Tp = std::__debug::array<std::__cxx11::basic_string<char>, 4ul>; long unsigned int _Nm = 2ul; std::__debug::array<_Tp, _Nm>::size_type = long unsigned int]’
     std::array<std::ostringstream, stats.size()> lines;
                                              ^
src/inventory_ui.cpp:1027:48: note: in template argument for type ‘long unsigned int’ 
     std::array<std::ostringstream, stats.size()> lines;
                                                ^
src/inventory_ui.cpp:1028:34: error: call to non-constexpr function ‘constexpr std::__debug::array<_Tp, _Nm>::size_type std::__debug::array<_Tp, _Nm>::size() const [with _Tp = std::__debug::array<std::__cxx11::basic_string<char>, 4ul>; long unsigned int _Nm = 2ul; std::__debug::array<_Tp, _Nm>::size_type = long unsigned int]’
     std::array<size_t, stats.size()> widths;
                                  ^
src/inventory_ui.cpp:1028:34: error: call to non-constexpr function ‘constexpr std::__debug::array<_Tp, _Nm>::size_type std::__debug::array<_Tp, _Nm>::size() const [with _Tp = std::__debug::array<std::__cxx11::basic_string<char>, 4ul>; long unsigned int _Nm = 2ul; std::__debug::array<_Tp, _Nm>::size_type = long unsigned int]’
src/inventory_ui.cpp:1028:36: note: in template argument for type ‘long unsigned int’ 
     std::array<size_t, stats.size()> widths;
                                    ^
src/inventory_ui.cpp:1031:16: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
         lines[i] << stats[i][0] << ' ';
                ^
src/inventory_ui.cpp:1036:60: error: request for member ‘begin’ in ‘widths’, which is of non-class type ‘int’
         std::transform( stats.begin(), stats.end(), widths.begin(),
                                                            ^
src/inventory_ui.cpp:1041:56: error: request for member ‘begin’ in ‘widths’, which is of non-class type ‘int’
         const size_t max_w = *std::max_element( widths.begin(), widths.end() );
                                                        ^
src/inventory_ui.cpp:1041:72: error: request for member ‘end’ in ‘widths’, which is of non-class type ‘int’
         const size_t max_w = *std::max_element( widths.begin(), widths.end() );
                                                                        ^
src/inventory_ui.cpp:1044:33: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
             if( max_w > widths[i] ) {
                                 ^
src/inventory_ui.cpp:1045:24: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
                 lines[i] << std::string( max_w - widths[i], ' ' );
                        ^
src/inventory_ui.cpp:1045:58: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
                 lines[i] << std::string( max_w - widths[i], ' ' );
                                                          ^
src/inventory_ui.cpp:1047:20: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
             lines[i] << stats[i][j];
                    ^
src/inventory_ui.cpp:1052:27: error: request for member ‘begin’ in ‘lines’, which is of non-class type ‘int’
     std::transform( lines.begin(), lines.end(), std::back_inserter( result ),
                           ^
src/inventory_ui.cpp:1052:42: error: request for member ‘end’ in ‘lines’, which is of non-class type ‘int’
     std::transform( lines.begin(), lines.end(), std::back_inserter( result ),
                                          ^
Makefile:646: recipe for target 'obj/inventory_ui.o' failed
make: *** [obj/inventory_ui.o] Error 1
