### ISSUE TITLE
Windows build is broken after #18697

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#18711]
In file included from src/action.cpp:16:0:
src/itype.h:653:38: error: missing initializer for member 'std::array<int, 10u>::_M_elems' [-Werror=missing-field-initializers]
     std::array<int, NUM_DT> melee = {};
                                      ^

**Comment by mutability** [comment]
Also warns on: gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

```
src/itype.h:653:38: warning: missing initializer for member ‘std::__debug::array<int, 10ul>::_M_elems’ [-Wmissing-field-initializers]
     std::array<int, NUM_DT> melee = {};
```
