### ISSUE TITLE
bugs preventing PR build

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#20093]
>In file included from src/defense.cpp:13:
src/monstergenerator.h:72:16: error: struct 'mattack_actor' was previously declared as a class [-Werror,-Wmismatched-tags]
        friend struct mattack_actor;
               ^
src/mattack_common.h:13:7: note: previous use is here
class mattack_actor {
      ^
src/monstergenerator.h:72:16: note: did you mean class here?
        friend struct mattack_actor;
               ^~~~~~
               class
1 error generated.
make: *** [obj/defense.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/game.cpp:33:
src/monstergenerator.h:72:16: error: struct 'mattack_actor' was previously declared as a class [-Werror,-Wmismatched-tags]
        friend struct mattack_actor;
               ^
src/mattack_common.h:13:7: note: previous use is here
class mattack_actor {
      ^
src/monstergenerator.h:72:16: note: did you mean class here?
        friend struct mattack_actor;
               ^~~~~~
               class

**Comment by keyspace** [comment]
Probable cause #20092 - ping @Coolthulhu.

**Comment by keyspace** [comment]
Example failed log: http://ci.narc.ro/job/Cataclysm-Jently/68118//consoleText

Builds fine using `gcc version 6.2.1 20160830 (GCC)` on 64-bit Arch Linux and current git master (`0.C-20787-g6ec9931702`).

**Comment by keyspace** [comment]
Possible underlying cause is a stale `ccache` (false positive hit). Ping @narc0tiq.

I use `ccache`, too, - not via `Makefile`'s `CCACHE`, but by expanding `PATH` to match `ccache`'s compiler binaries.

**Comment by narc0tiq** [comment]
http://ci.narc.ro/job/Cataclysm-Jently/68118/ started building at 06:20 UTC; PR #20092 was merged at 06:38 UTC. The former cannot have included the bugfix from the latter.

Since the last 20 builds of [the PR builder](http://ci.narc.ro/job/Cataclysm-Jently/) all show successful, can I assume there is no actual issue?

**Comment by DangerNoodle** [comment]
Strange. Uncertain as to the cause now that commits are generating as successful.

**Comment by keyspace** [comment]
@narc0tiq The compilation seems to have started at 06:37:39 UTC, could it have finished in time before 06:38? I suspect @Coolthulhu merged without waiting for the check to pass, knowing that it would pass, and that could have fudged up `ccache`'s cache.

I've also had weird stuff happen with `make -jX` and `ccache`, but that's anecdotal.

This comment is not to blame anyone! The above is idle guesswork.

Only coherent suggestion I have is more timestamps everywhere.

**Comment by BorkBorkGoesTheCode** [comment]
Looks like it's finished

**Comment by narc0tiq** [comment]
> some pull requests (such as mine at #19905) are still citing this error

It takes a long time for Jenkins to rebuild all the pull requests after a change to master; and master changes often enough that it doesn't always have a chance to do them all before having to start over.


> The compilation seems to have started at 06:37:39 UTC, could it have finished in time before 06:38?

It doesn't matter. When you start fetching something, it can't change halfway through the fetch. There is no opportunity to "fudge up" any cache, because anything pushed to master after the fetch doesn't exist yet.


> what this seems like to me is that builds used the "old" (pre-#20092) code, but the "new" ccache compiled object,

My understanding is that the builds used the old code, which failed to compile due to an error. The error was later resolved. The builds compiled thereafter.

**Comment by DangerNoodle** [comment]
Ah, I see. My apologies for that.
