### ISSUE TITLE
Compilation failure on mac os due to copy elision problems

### ISSUE THREAD

**Issue by patternoia** [CleverRaven/Cataclysm-DDA#15988]
Supposedly caused by 2cf599c9

4 errors of this kind: src/npcmove.cpp:920:29: error: moving a temporary object prevents copy elision

Full compiler dump here https://gist.github.com/anonymous/5088612955352fc592c8b646020aeef8

**Comment by kevingranade** [comment]
Yes, in general we're way too move-happy, we should only be doing it when
there's a demonstrable performance issue it addresses.

**Comment by patternoia** [comment]
@kevingranade I've tried to hot-fix the compilation by removing std::move (see below) and saw no crashes or instabilities.

const auto it_loc = std::move( node->pick_reload_ammo( *this ).ammo );
to
const auto it_loc = node->pick_reload_ammo( *this ).ammo;

If it is okay, I will create a pull request with these fixes.

**Comment by FlaKougar** [comment]
I've also been running on mac with those changes and seems fine to me.

**Comment by kevingranade** [comment]
Please do, that is generally a safe change to make.
