### PR TITLE
Fix Lua build on Mac (maybe)

### LINKED ISSUE #13990: Lua generated bindings do not compile on Mac OS
I'm trying to get a full build working on Mac OS with all the optional stuff. I cannot get the lua generated bindings to compile. If you could help me fix this problem, it would be much appreciated. Here is the build log:

```
Remys-MacBook-Pro:Cataclysm-DDA remyroy$ make app -j2 NATIVE=osx OSX_MIN=10.7 RELEASE=1 TILES=1 FRAMEWORK=1 LOCALIZE=0 CLANG=1 SOUND=1 LUA=1
rm -rf Cataclysm.app
clang++  -DRELEASE -DMACOSX -DOSX_SDL_FW -DTILES -ffast-math -O3 -Werror -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-missing-braces   -Werror -stdlib=libc++ --std=c++11 -MMD -mmacosx-version-min=10.7 -I/Library/Frameworks/SDL2_mixer.framework/Headers -I/Users/remyroy/Library/Frameworks/SDL2_mixer.framework/Headers -DSDL_SOUND -I/usr/local/include -DLUA -F/Library/Frameworks -F/Users/remyroy/Library/Frameworks -I/Library/Frameworks/SDL2.framework/Headers -I/Users/remyroy/Library/Frameworks/SDL2.framework/Headers -I/Library/Frameworks/SDL2_image.framework/Headers -I/Users/remyroy/Library/Frameworks/SDL2_image.framework/Headers -I/Library/Frameworks/SDL2_ttf.framework/Headers -I/Users/remyroy/Library/Frameworks/SDL2_ttf.framework/Headers -c src/catalua.cpp -o obj/tiles/catalua.o
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19244:53: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<overmap*>::MRMap LuaValue<overmap*>::READ_MEMBERS = {
                                                    ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19247:53: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<overmap*>::MWMap LuaValue<overmap*>::WRITE_MEMBERS = {
                                                    ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19267:49: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<field*>::MRMap LuaValue<field*>::READ_MEMBERS = {
                                                ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19270:49: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<field*>::MWMap LuaValue<field*>::WRITE_MEMBERS = {
                                                ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19284:49: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<Skill*>::MRMap LuaValue<Skill*>::READ_MEMBERS = {
                                                ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19287:49: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<Skill*>::MWMap LuaValue<Skill*>::WRITE_MEMBERS = {
                                                ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19457:51: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<trap_id>::MRMap LuaValue<trap_id>::READ_MEMBERS = {
                                                  ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19460:51: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<trap_id>::MWMap LuaValue<trap_id>::WRITE_MEMBERS = {
                                                  ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19482:53: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<w_point*>::MWMap LuaValue<w_point*>::WRITE_MEMBERS = {
                                                    ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19502:55: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<map_stack>::MRMap LuaValue<map_stack>::READ_MEMBERS = {
                                                      ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19505:55: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<map_stack>::MWMap LuaValue<map_stack>::WRITE_MEMBERS = {
                                                      ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19663:45: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<map*>::MRMap LuaValue<map*>::READ_MEMBERS = {
                                            ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19666:45: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<map*>::MWMap LuaValue<map*>::WRITE_MEMBERS = {
                                            ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19701:47: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<trap*>::MWMap LuaValue<trap*>::WRITE_MEMBERS = {
                                              ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19715:63: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<species_type*>::MRMap LuaValue<species_type*>::READ_MEMBERS = {
                                                              ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19718:63: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<species_type*>::MWMap LuaValue<species_type*>::WRITE_MEMBERS = {
                                                              ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19735:51: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<furn_id>::MRMap LuaValue<furn_id>::READ_MEMBERS = {
                                                  ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:19738:51: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<furn_id>::MWMap LuaValue<furn_id>::WRITE_MEMBERS = {
                                                  ^               ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from src/catalua.cpp:955:
src/lua/catabindings.cpp:20322:59: error: chosen constructor is explicit in
      copy-initialization
const LuaValue<trap_str_id>::MRMap LuaValue<trap_str_id>::READ_MEMBERS = {
                                                          ^              ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [obj/tiles/catalua.o] Error 1
```
I'm using Lua 5.2.4 from homebrew. I'm also posting [a pastebin of the generated catabindings.cpp](http://pastebin.ubuntu.com/13235054/).

Let me know if you have any clue. Thanks.

### PR DESCRIPTION
**Pull request by BevapDin**
Current code works fine with LLVM/clang version 3.7.0, for me and for Jenkins, but we don't want to exclude anybody, not even Mac users.

This may fix #13990, but I can't test it.

Instead of `Type x = { ... };` it is now `Type x{ ... }`.

This hopefully fixes the "chosen constructor is explicit in copy-initialization" bug, as there is no copy initialization anymore.

### CODE REVIEW

**Comment by remyroy** [comment]
I'll check that in the next few minutes.

**Comment by remyroy** [comment]
I was just able to fully compile CDDA with Lua support on on Mac OSX 10.9.5. This fixes #13990. Thanks.

**Comment by remyroy** [comment]
[Here are a few tests I completed](http://imgur.com/a/cRxL6) to make sure it works.
