### ISSUE TITLE
Build failing in Code Blocks.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#15182]
It seems to fail for me ever since https://github.com/CleverRaven/Cataclysm-DDA/pull/15057 was merged.

----
**Error log:**

obj\Release\src\game.o:game.cpp:(.text+0x68e03): undefined reference to `player::rate_action_eat(item const&) const'

obj\Release\src\iexamine.o:iexamine.cpp:(.text+0x13d71): undefined reference to `player::eat(item&, bool)'

obj\Release\src\item.o:item.cpp:(.text+0xbe11): undefined reference to `player::can_eat(item const&, bool, bool) const'

obj\Release\src\item.o:item.cpp:(.text+0x26a8c): undefined reference to `player::nutrition_for(it_comest const*) const'

obj\Release\src\item.o:item.cpp:(.text+0x26af8): undefined reference to `player::nutrition_for(it_comest const*) const

**Comment by macrosblackd** [comment]
Looks like consumption.h/cpp needs to be added to the project

**Comment by chaosvolt** [comment]
And I just got whined at by @kevingranade because I submitted a pull request after being unable to compile-test due to this issue. Glorious.

**Comment by kevingranade** [comment]
That's it, you're out.

**Comment by chaosvolt** [comment]
Yes, I know I overreacted. But that STARTED because you proceeded to get on my case because you failed to pay any attention to the fact that I had in fact compiled sucessfully prior to that.

You berated me in ignorance. Were you EXPECTING me to not get offended, or to not at least be annoyed at it?
