### ISSUE TITLE
Unable to compile with clang 11.0.0 on MacOS due deprecated method

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#35192]
# Describe the bug
Compilation fails on npcmove.cpp, due to random_shuffle being deprecated. 

# Steps To Reproduce
Run compilation and get the following error(s):
```
src/npcmove.cpp:3956:14: error: 'random_shuffle<std::__1::__wrap_iter<int_id<oter_type_t> *> >' is deprecated [-Werror,-Wdeprecated-declarations]
        std::random_shuffle( loc_list.begin(), loc_list.end() );
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2982:1: note: 'random_shuffle<std::__1::__wrap_iter<int_id<oter_type_t> *> >' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX14 void
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1107:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX14'
#  define _LIBCPP_DEPRECATED_IN_CXX14 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 error generated.
make: *** [obj/tiles/npcmove.o] Error 1
```

# Expected behavior
Compilation should finish.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

Running the following clang:
```
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
```
Using the following command line to build:
`make NATIVE=osx OSX_MIN=10.14 RELEASE=1 TILES=1 LOCALIZE=0 CLANG=1 LINTJSON=0 CCACHE=1 -j2`

# Additional context

We spoke about this on the discord, and the random_shuffle method should be replaced with something that isn't deprecated. This is unfortunately beyond my current knowledge, and as such I open this issue so it can be addressed.
