### PR TITLE
Fix some things that prevented compilation with MSVC

### LINKED ISSUE #22233: MinGW tiles build warnings
Apparently MinGW in MSYS2 doesn't like `%ll` format arguments introduced in #22215.

EDIT: It may be related to 32-bit vs 64-bit builds. I got 64-bit build working, but the 32-bit one produces the errors below.
```
gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 7.2.0
```

```
In file included from src/string_formatter.h:7:0,
                 from src/ret_val.h:5,
                 from src/item.h:20,
                 from src/inventory.h:6,
                 from src/character.h:7,
                 from src/player.h:5,
                 from src/sdltiles.cpp:10:
src/compatibility.h: In function 'std::__cxx11::string to_string(long long int)':
src/compatibility.h:53:39: error: unknown conversion type character 'l' in format [-Werror=format=]
     snprintf( buffer, size, "%lld", n );
                                       ^
src/compatibility.h:53:39: error: too many arguments for format [-Werror=format-extra-args]
src/compatibility.h:53:39: error: unknown conversion type character 'l' in format [-Werror=format=]
src/compatibility.h:53:39: error: too many arguments for format [-Werror=format-extra-args]
src/compatibility.h: In function 'std::__cxx11::string to_string(long long unsigned int)':
src/compatibility.h:62:39: error: unknown conversion type character 'l' in format [-Werror=format=]
     snprintf( buffer, size, "%llu", n );
                                       ^
src/compatibility.h:62:39: error: too many arguments for format [-Werror=format-extra-args]
src/compatibility.h:62:39: error: unknown conversion type character 'l' in format [-Werror=format=]
src/compatibility.h:62:39: error: too many arguments for format [-Werror=format-extra-args]
```

### PR DESCRIPTION
**Pull request by nshcat**
This PR fixes (partially) 22233 (the VS bugs mentioned in the comments).

The new string formatter (located in `string_formatter.h`) used non-standard, gcc-style attribute specifiers which are not supported by VisualStudio. I replaced those with C++11 attributes.

Additionally, there is `constexpr`-related compiler bug when dealing with delegating constructors in MSVC, which occured in `optional.h`. That got fixed, too.

I tried to fix the MSYS2 erros mentioned in #22233, but I **could not** reproduce those on a current installation of MSYS2.

### CODE REVIEW

File: src/string_formatter.h [hunk 1]
```diff
@@ -194,7 +195,8 @@ class string_formatter
         // Helper for common logic in @ref read_width and @ref read_precision.
         cata::optional<int> read_number_or_argument_index();
         /// Throws an exception containing the given message and the @ref format.
-        void __attribute__( ( noreturn ) ) throw_error( const std::string &msg ) const;
+		[[noreturn]]
```
Comment (Coolthulhu) [inline src/string_formatter.h]: Tabs

**Comment by Coolthulhu** [comment]
Don't use "fixes #issue_number_here" phrase in the PR description for partial fixes - github detects that phrase and will automatically close the issue if the PR is merged, meaning that if the tester isn't careful, the issue may be left closed despite not being fixed.

**Comment by nshcat** [comment]
I removed the "#<issue_nr>" in the main post and fixed the usage of tabs. Thanks for the feedback.
