### ISSUE TITLE
Build failure on FreeBSD

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#12414]
In file included from src/veh_typedef.cpp:1:
In file included from src/veh_type.h:5:
src/int_id.h:92:20: error: implicit instantiation of undefined template 'std::__1::hash<int>'
            return hash<int>()( v.to_i() );
                   ^
/usr/include/c++/v1/memory:3062:29: note: template is declared here
template <class _Tp> struct hash;

Possibly introduced by commit 14b2e516755ca7a20b8a27a32c83215a7defff7b

**Comment by mugling** [comment]
$ clang++ --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.1
Thread model: posix

**Comment by jakwings** [comment]
Similar error on OSX MacPorts build (solved with the patch from #12415):

```sh
make NATIVE=osx OSX_MIN=10.10 CLANG=1 RELEASE=1 LOCALIZE=1 LANGUAGES="zh_CN" LUA=1 MACPORTS=1
```

```
#define VERSION "0.C-2872-gb527b26"
...
clang++ -DRELEASE -DMACOSX -DLOCALIZE -O3 -Werror -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-missing-braces   -Werror -stdlib=libc++ --std=c++11 -MMD -mmacosx-version-min=10.10 -I/opt/local/include   -I/opt/local/include  -DLUA -c src/veh_typedef.cpp -o obj/veh_typedef.o
In file included from src/veh_typedef.cpp:1:
In file included from src/veh_type.h:5:
src/int_id.h:92:20: error: implicit instantiation of undefined template 'std::__1::hash<int>'
            return hash<int>()( v.to_i() );
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3065:29: note: template is declared here
template <class _Tp> struct hash;
                            ^
1 error generated.
make: *** [obj/veh_typedef.o] Error 1
```

$ clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
