### PR TITLE
Change names of ot_match_type to lowercase

### LINKED ISSUE #31954: PREFIX make variable no longer works
Spew lots of errors in src/enums.h.
13a0206c83a9966e54740fa60ff61a7c87eba20a is the first bad commit

### PR DESCRIPTION
**Pull request by BevapDin**
```Summary: None```

This avoids a conflict with the preprocessor macro PREFIX (see Makefile).

All names of the enumeration have been changed for consistency. The translation-to-string map keeps the uppercase names for compatibility with existing JSON data.

Fixes #31954.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Using `type` causes ambiguity in certain environments now:

```
src/overmap.cpp: In function ‘om_direction::type rotate_internal(om_direction::type, int)’:
src/overmap.cpp:3759:16: error: reference to ‘type’ is ambiguous
     if( dir == type::invalid ) {
                ^
In file included from src/item.h:21:0,
                 from src/inventory.h:18,
                 from src/basecamp.h:13,
                 from src/overmap.h:19,
                 from src/overmap.cpp:2:
src/enums.h:44:5: note: candidates are: ot_match_type type
     type,
     ^
In file included from src/overmap.cpp:1:0:
src/omdata.h:48:12: note:                 enum class om_direction::type
 enum class type : int {
            ^
Makefile:791: recipe for target 'obj/overmap.o' failed
make: *** [obj/overmap.o] Error 1
make: *** Waiting for unfinished jobs....
```

We should probably add namespace prefixes.
