### ISSUE TITLE
Compiling with Astyle 3.1 - Errors

### ISSUE THREAD

**Issue by DaAngus** [CleverRaven/Cataclysm-DDA#29464]
**Describe the bug**  
I tried to compile with linux and Astyle 3.1-1
```

$ make -j4 CLANG=1 CCACHE=1 NATIVE=linux64 RELEASE=1 TILES=1 
astyle -V: Artistic Style Version 3.1
#define VERSION "0.D"
CCACHE_CPP2=1 ccache clang++ -ffast-math -Os -Wall -Wextra -fsigned-char -Werror -std=c++11 -MMD -MP -m64 -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -Itools/format -Isrc tools/format/format.cpp src/json.cpp -o tools/format/json_formatter.cgi
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DTILES -DBACKTRACE -DLOCALIZE -ffast-math -Os -Wall -Wextra -fsigned-char -Werror -std=c++11 -MMD -MP -m64 -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -c src/action.cpp -o obj/tiles/action.o
astyle regressions found.
Formatted  src/game.cpp
make: *** [Makefile:994: astyle-check] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/action.cpp:23:
In file included from src/vehicle.h:13:
src/clzones.h:244:23: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( zone_manager && ) = default;
                      ^
src/clzones.h:220:19: note: move assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type 'const int'
        const int MAX_DISTANCE = 10;
                  ^
src/clzones.h:245:23: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( const zone_manager & ) = default;
                      ^
src/clzones.h:220:19: note: copy assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type 'const int'
        const int MAX_DISTANCE = 10;
                  ^
2 errors generated.
make: *** [Makefile:768: obj/tiles/action.o] Error 1
or 1

```
I always try to give detailed reports but here I don't know whats needed or helpful...

**Comment by kevingranade** [comment]
The astyle issue is happening here
https://github.com/CleverRaven/Cataclysm-DDA/blob/92e8531243ecf39e16a65589e713436b9522ebf2/src/game.cpp#L3189-L3192

3.0.1, which we are still using on the main build server, has a bug that causes it to indent this improperly.  3.1 corrects it, but then it doesn't match.

For the time being we can just...
I just did it, no idea why I'm telling someone else to do it.
