### ISSUE TITLE
Windows builds are broken

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17742]
Windows buils are broken again in build 5266, related to #17732 
```
src/player_activity.cpp: In copy constructor 'player_activity::player_activity(const player_activity&)':
src/player_activity.cpp:36:1: error: base class 'class JsonSerializer' should be explicitly initialized in the copy constructor
 player_activity::player_activity( const player_activity &rhs )
 ^
src/player_activity.cpp:36:1: error: base class 'class JsonDeserializer' should be explicitly initialized in the copy constructor
```

**Comment by RealZogzog** [comment]
got the same errors on Ubuntu 14.04 + gcc 4.8.4

**Comment by Phanta** [comment]
The copy-constructor introduced in #17732 is missing constructor calls for its base classes `JsonSerializer` and `JsonDeserializer`. Following patch should fix this.
```diff
diff --git a/src/player_activity.cpp b/src/player_activity.cpp
index 98eb3fb..611a95e 100644
--- a/src/player_activity.cpp
+++ b/src/player_activity.cpp
@@ -34,7 +34,8 @@ player_activity::player_activity( activity_type t, int turns, int Index, int pos
 }
 
 player_activity::player_activity( const player_activity &rhs )
-    : type( rhs.type ), moves_total( rhs.moves_total ), moves_left( rhs.moves_left ),
+    : JsonSerializer(), JsonDeserializer(),
+      type( rhs.type ), moves_total( rhs.moves_total ), moves_left( rhs.moves_left ),
       index( rhs.index ), position( rhs.position ), name( rhs.name ),
       ignore_trivial( rhs.ignore_trivial ), values( rhs.values ), str_values( rhs.str_values ),
       coords( rhs.coords ), placement( rhs.placement ),
```

**Comment by mugling** [comment]
Thanks for the report. Fixed in `master`
