### ISSUE TITLE
Unable to compile wincurse.cpp

### ISSUE THREAD

**Issue by Hymore246** [CleverRaven/Cataclysm-DDA#32858]
# Describe the bug

I pulled the most recent update from master, get the following error when I compile:

```
||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\wincurse.cpp||In function 'void cata_cursesport::curses_drawwindow(const catacurses::window&)':|
C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\wincurse.cpp|417|error: 'struct cata_cursesport::WINDOW' has no member named 'x'|
C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\wincurse.cpp|418|error: 'struct cata_cursesport::WINDOW' has no member named 'x'|
C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\wincurse.cpp|423|error: 'struct cata_cursesport::WINDOW' has no member named 'y'|
C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\wincurse.cpp|435|error: 'struct cata_cursesport::WINDOW' has no member named 'x'|
C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\wincurse.cpp|436|error: 'struct cata_cursesport::WINDOW' has no member named 'y'|
||=== Build finished: 5 error(s), 0 warning(s) (7 minute(s), 43 second(s)) ===|
```

# Steps To Reproduce

1. Download most recent master build
2. Attempt to build and run in Code:Blocks
3. Errors will appear during compilation.

# Expected behavior

Fresh code from master should compile without warnings or errors.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-6111-gfa057fd (tiles)
 - IDE: Code:Blocks

# Additional context
I think this is being caused by #32017 but I'm not 100% sure.

**Comment by AMurkin** [comment]
Should be fixed with #33094
