### ISSUE TITLE
Failure to build from source

### ISSUE THREAD

**Issue by lucanLepus** [CleverRaven/Cataclysm-DDA#23243]
Game version: 52ac52bbf2
Operating system: Arch Linux, gcc 7.3.0 

### Expected behavior
Code compiles

### Actual behavior
Code fails to compile, build output excerpt:
```
In file included from /usr/include/c++/7.3.0/debug/stl_iterator.h:32:0,
                 from /usr/include/c++/7.3.0/bits/stl_iterator.h:1257,
                 from /usr/include/c++/7.3.0/bits/stl_algobase.h:67,
                 from /usr/include/c++/7.3.0/bits/char_traits.h:39,
                 from /usr/include/c++/7.3.0/string:40,
                 from /usr/include/c++/7.3.0/stdexcept:39,
                 from /usr/include/c++/7.3.0/array:39,
                 from /usr/include/c++/7.3.0/tuple:39,
                 from /usr/include/c++/7.3.0/functional:54,
                 from src/visitable.h:5,
                 from src/character.h:5,
                 from src/player.h:5,
                 from src/npc.h:5,
                 from src/npcmove.cpp:1:
/usr/include/c++/7.3.0/debug/helper_functions.h: In instantiation of ‘typename __gnu_debug::_Distance_traits<_Iterator>::__type __gnu_debug::__get_distance(const _Iterator&, const _Iterator&, std::input_iterator_tag) [with _Iterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’:
/usr/include/c++/7.3.0/debug/helper_functions.h:101:28:   required from ‘typename __gnu_debug::_Distance_traits<_Iterator>::__type __gnu_debug::__get_distance(const _Iterator&, const _Iterator&) [with _Iterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’
/usr/include/c++/7.3.0/debug/helper_functions.h:127:30:   required from ‘bool __gnu_debug::__valid_range_aux(const _InputIterator&, const _InputIterator&, typename __gnu_debug::_Distance_traits<_Iterator>::__type&, std::__false_type) [with _InputIterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’
/usr/include/c++/7.3.0/debug/helper_functions.h:156:31:   required from ‘bool __gnu_debug::__valid_range(const _InputIterator&, const _InputIterator&, typename __gnu_debug::_Distance_traits<_Iterator>::__type&) [with _InputIterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’
/usr/include/c++/7.3.0/debug/helper_functions.h:164:27:   required from ‘bool __gnu_debug::__valid_range(const _InputIterator&, const _InputIterator&) [with _InputIterator = tripoint_range::point_generator]’
/usr/include/c++/7.3.0/bits/stl_algo.h:746:7:   required from ‘_OIter std::copy_if(_IIter, _IIter, _OIter, _Predicate) [with _IIter = tripoint_range::point_generator; _OIter = std::back_insert_iterator<std::__debug::vector<tripoint> >; _Predicate = npc::move_away_from(const std::__debug::vector<sphere>&, bool)::<lambda(const tripoint&)>]’
src/npcmove.cpp:1809:7:   required from here
/usr/include/c++/7.3.0/debug/helper_functions.h:92:17: error: no match for ‘operator==’ (operand types are ‘const tripoint_range::point_generator’ and ‘const tripoint_range::point_generator’)
       if (__lhs == __rhs)
           ~~~~~~^~~~~~~~
```

### Steps to reproduce the behavior
make clean && make

### Misc info
a quick git bisect points towards c12dd939ff8cdb6229561bcd10f3a88ee78bb8f0 as the first bad commit

**Comment by lucanLepus** [comment]
just realized #23235 probably fixes this
