### ISSUE TITLE
Can't compile latest.

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13869]
825e0df (though I was also having it with adbb9d3 ) - Can't compile on ubuntu 15.10 32bit gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010

make CCACHE=1 TILES=1 SOUND=1 LUA=1 RELEASE=1

Error occurs after linker
obj/tiles/game.o: In function `game::handle_action()':
game.cpp:(.text+0x635e1): undefined reference to `game::draw_overmap()'

**Comment by Midaychi** [comment]
Ok. Nevermind. This was on my end. I like commenting out the debug menu and I put the */ on the wrong line.
