### ISSUE TITLE
Current master (8a5215) doesn't build with clang

### ISSUE THREAD

**Issue by MarcusVoelker** [CleverRaven/Cataclysm-DDA#18493]
```
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
```

Tested on Gentoo with clang version 3.9.0

**Comment by mugling** [comment]
Any more surrounding context?

**Comment by MarcusVoelker** [comment]
For
```
make -j5 CLANG=1 RELEASE=1
```
,
```
/bin/sh: astyle: command not found
mkdir -p obj
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/monattack.cpp -o obj/monattack.o
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/mapgen.cpp -o obj/mapgen.o
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/item_factory.cpp -o obj/item_factory.o
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/coordinate_conversions.cpp -o obj/coordinate_conversions.o
#define VERSION "0.C-18718-g240f657"
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/crafting.cpp -o obj/crafting.o
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/active_item_cache.cpp -o obj/active_item_cache.o
In file included from src/item_factory.cpp:1:
In file included from src/item_factory.h:13:
In file included from src/itype.h:8:
In file included from src/pldata.h:6:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/player.cpp -o obj/player.o
In file included from src/monattack.cpp:2:
In file included from src/monster.h:4:
In file included from src/creature.h:4:
In file included from src/pldata.h:6:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
In file included from src/crafting.cpp:1:
In file included from src/crafting.h:4:
In file included from src/item.h:11:
In file included from src/visitable.h:10:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
Makefile:638: recipe for target 'obj/monattack.o' failed
make: *** [obj/monattack.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
Makefile:638: recipe for target 'obj/item_factory.o' failed
make: *** [obj/item_factory.o] Error 1
1 error generated.
Makefile:638: recipe for target 'obj/crafting.o' failed
make: *** [obj/crafting.o] Error 1
In file included from src/mapgen.cpp:1:
In file included from src/map.h:12:
In file included from src/item.h:11:
In file included from src/visitable.h:10:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
Makefile:638: recipe for target 'obj/mapgen.o' failed
make: *** [obj/mapgen.o] Error 1
In file included from src/player.cpp:1:
src/player.h:856:100: error: instantiation of variable 'string_id<Skill>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        bool can_use( const item& it, bool interactive = true, const skill_id &context = skill_id::NULL_ID ) const;
                                                                                                   ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/player.h:856:100: note: add an explicit instantiation declaration to suppress this warning if 'string_id<Skill>::NULL_ID' is explicitly instantiated in another translation unit
        bool can_use( const item& it, bool interactive = true, const skill_id &context = skill_id::NULL_ID ) const;
                                                                                                   ^
1 error generated.
Makefile:638: recipe for target 'obj/player.o' failed
make: *** [obj/player.o] Error 1
```

**Comment by illi-kun** [comment]
I've tested current master with ```clang 3.8``` and it builds fine.
@MarcusVoelker could you confirm that this is still an issue for you? (If so, try to ```make clean``` and re-build everything from scratch).

**Comment by MarcusVoelker** [comment]
Updated master, clang version 3.9.0, same command line as above, after clean:

```
clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -I/usr/include/ncursesw -c src/monattack.cpp -o obj/monattack.o
In file included from src/monattack.cpp:2:
In file included from src/monster.h:4:
In file included from src/creature.h:4:
In file included from src/pldata.h:6:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
Makefile:638: recipe for target 'obj/monattack.o' failed
make: *** [obj/monattack.o] Error 1
```

**Comment by MehMuffin** [comment]
experiencing the same sort of error

`
make -j8 CLANG=1 RELEASE=1 CCACHE=1
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/mapdata.cpp -o obj/mapdata.o
Cannot lint JSON, missing usable perl binary and/or p5-JSON module
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/scent_map.cpp -o obj/scent_map.o
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/vehicle_group.cpp -o obj/vehicle_group.o
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/mission.cpp -o obj/mission.o
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/npc.cpp -o obj/npc.o
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/mutation.cpp -o obj/mutation.o
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/monstergenerator.cpp -o obj/monstergenerator.o
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -c src/sounds.cpp -o obj/sounds.o
In file included from src/scent_map.cpp:4:
In file included from src/map.h:12:
In file included from src/item.h:11:
In file included from src/visitable.h:10:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/scent_map.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/vehicle_group.cpp:1:
In file included from src/vehicle_group.h:5:
In file included from src/mapgen.h:8:
In file included from src/mapdata.h:7:
In file included from src/iexamine.h:15:
src/string_id.h:66:50: error: instantiation of variable 'string_id<ter_t>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/mapdata.h:70:50: note: in instantiation of member function 'string_id<ter_t>::string_id' requested here
                      drop_group("EMPTY_GROUP"), ter_set(NULL_ID), furn_set(NULL_ID) {};
                                                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<ter_t>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/vehicle_group.o] Error 1
In file included from src/mapdata.cpp:1:
In file included from src/mapdata.h:7:
In file included from src/iexamine.h:15:
src/string_id.h:66:50: error: instantiation of variable 'string_id<harvest_list>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/harvest.h:29:26: note: in instantiation of member function 'string_id<harvest_list>::string_id' requested here
        harvest_list() : id_( NULL_ID ) {}
                         ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<harvest_list>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/mapdata.o] Error 1
In file included from src/mutation.cpp:1:
In file included from src/mutation.h:8:
In file included from src/damage.h:5:
src/string_id.h:66:50: error: instantiation of variable 'string_id<activity_type>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/player_activity.h:104:35: note: in instantiation of member function 'string_id<activity_type>::string_id' requested here
        player_activity() : type( activity_id( NULL_ID ) ) { }
                                  ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<activity_type>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/mutation.o] Error 1
In file included from src/monstergenerator.cpp:1:
In file included from src/monstergenerator.h:6:
src/string_id.h:66:50: error: instantiation of variable 'string_id<harvest_list>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/harvest.h:29:26: note: in instantiation of member function 'string_id<harvest_list>::string_id' requested here
        harvest_list() : id_( NULL_ID ) {}
                         ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<harvest_list>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/monstergenerator.o] Error 1
In file included from src/mission.cpp:1:
In file included from src/mission.h:7:
In file included from src/omdata.h:9:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/mission.o] Error 1
In file included from src/sounds.cpp:5:
In file included from src/map.h:12:
In file included from src/item.h:11:
In file included from src/visitable.h:10:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/sounds.o] Error 1
In file included from src/npc.cpp:1:
In file included from src/npc.h:4:
In file included from src/player.h:4:
In file included from src/character.h:4:
In file included from src/visitable.h:10:
src/string_id.h:66:50: error: instantiation of variable 'string_id<activity_type>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/player_activity.h:104:35: note: in instantiation of member function 'string_id<activity_type>::string_id' requested here
        player_activity() : type( activity_id( NULL_ID ) ) { }
                                  ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<activity_type>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [Makefile:654: obj/npc.o] Error 1
`

**Comment by codemime** [comment]
It's a subsequent issue caused by #17197.
