### ISSUE TITLE
error: ‘class map’ has no member named ‘visibility_cache’

### ISSUE THREAD

**Issue by pouar** [CleverRaven/Cataclysm-DDA#12421]
```
src/cata_tiles.cpp: In member function ‘void cata_tiles::draw(int, int, const tripoint&, int, int)’:
src/cata_tiles.cpp:618:42: error: ‘class map’ has no member named ‘visibility_cache’
             draw_single_tile( temp, g->m.visibility_cache[x][y], cache );
```

**Comment by pouar** [comment]
did a git bisect and found out it was introduced here
0c928f2046b1ba27667f5e811781e71e5b12921b
