### PR TITLE
Updated required Lua version in COMPILING*.md

### PR DESCRIPTION
**Pull request by Maykeye**
Documentation mentions that required version of Lua is 5.1,
currently it requires 5.2 and can't be build with 5.1

### CODE REVIEW

**Comment by BevapDin** [comment]
What's the error message that you get with Lua 5.1, because it works fine for me with Lua 5.1.4 (Linux, 32bit). There is a bit of compatibility code for Lua 5.1 in catalua.cpp (inside the `#LUA_VERSION_NUM < 502` blocks), that makes it work.

If Lua 5.1 is really abandoned, the compatibility code should be removed as well.

**Comment by Maykeye** [comment]
> src/catalua.h:13:17: fatal error: lua.h: No such file or directory
> #include "lua.h"

Makefile mentions only lua5.2 and just some lua. When 5.1 installed  it doesn't work:

 % pkg-config  --cflags lua5.1
-I/usr/include/lua5.1  

% pkg-config  --cflags lua 
Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found

**Comment by macrosblackd** [comment]
You need to use lua5.1 for cflags

**Comment by Maykeye** [comment]
@macrosblackd  That's what was used before  53f43b3768f2 commit

% git diff 53f43b3768f2..53f43b3768f2^1 -- Makefile
..
-    CXXFLAGS += $(shell pkg-config --silence-errors --cflags lua-5.2)
+    LDFLAGS += $(shell pkg-config --silence-errors --libs lua5.1)

**Comment by macrosblackd** [comment]
the game compiles fine with lua5.1, if you're having issues, it's on your end.

**Comment by kevingranade** [comment]
@Maykeye if you change the cflags invocations back to lua5.1, does it work?
If so we either need the Makefile to somehow detect the installed version of lua, or provide an option to select it.

**Comment by Maykeye** [comment]
@kevingranade yes, it works this way. 

Also if I include both 5.1 and 5.2 in Makefile and  install both of them, game will link with both `-llua5.2  -llua5.1` successfully. I suspected linker would say that some functions were definted several times.

Maybe use `$(shell $(PKG_CONFIG) --silence-errors --libs lua5.2 || $(PKG_CONFIG) --silence-errors --libs lua5.1)`? It looks ugly, but chooses version and doesn't link several luas.

**Comment by kevingranade** [comment]
I'm thinking we should have it try version strings until it finds a match and then stop, which is pretty much what you're saying.
I'm trying to sort out doing that now.

**Comment by kevingranade** [comment]
Pretty sure I got this with #13353, feel free to reopen if that doesn't work.
