### PR TITLE
Fix Codeblocks compilation and contained food

### LINKED ISSUE #15173: Perishables in containers that do not prevent spoilage are no longer color-coded
Somewhat annoying as you typically want to consume perishables first.

### LINKED ISSUE #15182: Build failing in Code Blocks.
It seems to fail for me ever since https://github.com/CleverRaven/Cataclysm-DDA/pull/15057 was merged.

----
**Error log:**

obj\Release\src\game.o:game.cpp:(.text+0x68e03): undefined reference to `player::rate_action_eat(item const&) const'

obj\Release\src\iexamine.o:iexamine.cpp:(.text+0x13d71): undefined reference to `player::eat(item&, bool)'

obj\Release\src\item.o:item.cpp:(.text+0xbe11): undefined reference to `player::can_eat(item const&, bool, bool) const'

obj\Release\src\item.o:item.cpp:(.text+0x26a8c): undefined reference to `player::nutrition_for(it_comest const*) const'

obj\Release\src\item.o:item.cpp:(.text+0x26af8): undefined reference to `player::nutrition_for(it_comest const*) const

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #15173
Closes #15182

I didn't check the compilation part because I don't have a set up codeblocks installation, but so far just adding the new files to the file always worked.

Added missing perishable coloration to contained food.
Added a special case for canned food, since it doesn't rot even though its perishable.

### CODE REVIEW

**Comment by macrosblackd** [comment]
Could you add the consumption files to the src/CMakeLists.txt as well?

**Comment by chaosvolt** [comment]
Any idea on what the cause of the container-coloration bug was? I'm not sure what obscure change could've caused it.

File: src/item.cpp [hunk 1]
```diff
@@ -1870,9 +1871,11 @@ nc_color item::color_in_inventory() const
         switch( rating ) {
             case EDIBLE:
             case TOO_FULL:
-                if( is_going_bad() ) {
+                if( preserves ) {
+                    // Nothing, canned food won't rot
```
Comment (macrosblackd) [inline src/item.cpp]: Won't this prevent cans from showing perishable contents in their correct color?

Comment (chaosvolt) [inline src/item.cpp]: I think it's acceptable for the color to not display if the container will prevent rot entirely. I've always disliked not being able to sort out my canned food from my genuine perishables at a glance.

Comment (Coolthulhu) [inline src/item.cpp]: Canned food only really becomes perishable when removed from the can.
In most cases there is no good reason to un-can anything except during eating.
The old coloring was misleading - it hid the fact that cans prevent rot.

Comment (macrosblackd) [inline src/item.cpp]: I'm fine with that then.

Comment (chaosvolt) [inline src/item.cpp]: Which sounds like what I first assumed the bug was, I assumed it was a positive change before realizing that it also applied to containers that didn't preserve rot.

Then again, if we made cans need a can opener and made open cans no longer preserve food, I guess that technically would render it a moot point. XP
