### PR TITLE
Fix some clang-tidy errors

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
None

#### Purpose of change

Fix the following clang-tidy errors in iuse_actor.cpp introduced by #48462:

```
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/iuse_actor.cpp:2186:21: error: string concatenation results in allocation of unnecessary temporary strings; consider using 'operator+=' or 'string::append()' instead [performance-inefficient-string-concatenation,-warnings-as-errors]
                    spell_text = "<color_light_green>" + spell_text + _( " (Max)" ) + "</color>";
                    ^
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/iuse_actor.cpp:2188:21: error: string concatenation results in allocation of unnecessary temporary strings; consider using 'operator+=' or 'string::append()' instead [performance-inefficient-string-concatenation,-warnings-as-errors]
                    spell_text = "<color_yellow>" + spell_text + "</color>";
                    ^
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/iuse_actor.cpp:2192:21: error: string concatenation results in allocation of unnecessary temporary strings; consider using 'operator+=' or 'string::append()' instead [performance-inefficient-string-concatenation,-warnings-as-errors]
                    spell_text = "<color_light_blue>" + spell_text + "</color>";
```

Also fix another error in character.h, from #48917

```
Error: /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/character.h:2745:23: error: function 'Character::estimate_effect_dur' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
        time_duration estimate_effect_dur( const skill_id &relevant_skill, const efftype_id &effect,
                      ^
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/character.cpp:13235:26: note: the definition seen here
time_duration Character::estimate_effect_dur( const skill_id &relevant_skill,
                         ^
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/src/character.h:2745:23: note: differing parameters are named here: ('mimimum_error'), in definition: ('minimum_error')
        time_duration estimate_effect_dur( const skill_id &relevant_skill, const efftype_id &effect,
```

#### Describe the solution

1. Use string_format instead of concatenation.
2. Fix the typo (mimimum -> minimum).

#### Describe alternatives you've considered

Using += or string::append() as suggested. Doesn't really make sense since there is stuff to prepend as well. Also string_format is the typical way to generate formatted text.

Maybe replace `_( " (Max)" )` with `_( "Max" )` and put the parentheses in the untranslated string?

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
> Maybe replace _( " (Max)" ) with _( "Max" ) and put the parentheses in the untranslated string?

That is probably not the best for translation (though it could use context regardless).

**Comment by Qrox** [comment]
There's already a PR for this: #50084.

**Comment by eltank** [comment]
> There's already a PR for this: #50084.

Awesome. I will close this one then.
