### PR TITLE
Add equality operator to tripoint_range.

### LINKED ISSUE #23243: Failure to build from source
Game version: 52ac52bbf2
Operating system: Arch Linux, gcc 7.3.0 

### Expected behavior
Code compiles

### Actual behavior
Code fails to compile, build output excerpt:
```
In file included from /usr/include/c++/7.3.0/debug/stl_iterator.h:32:0,
                 from /usr/include/c++/7.3.0/bits/stl_iterator.h:1257,
                 from /usr/include/c++/7.3.0/bits/stl_algobase.h:67,
                 from /usr/include/c++/7.3.0/bits/char_traits.h:39,
                 from /usr/include/c++/7.3.0/string:40,
                 from /usr/include/c++/7.3.0/stdexcept:39,
                 from /usr/include/c++/7.3.0/array:39,
                 from /usr/include/c++/7.3.0/tuple:39,
                 from /usr/include/c++/7.3.0/functional:54,
                 from src/visitable.h:5,
                 from src/character.h:5,
                 from src/player.h:5,
                 from src/npc.h:5,
                 from src/npcmove.cpp:1:
/usr/include/c++/7.3.0/debug/helper_functions.h: In instantiation of ‘typename __gnu_debug::_Distance_traits<_Iterator>::__type __gnu_debug::__get_distance(const _Iterator&, const _Iterator&, std::input_iterator_tag) [with _Iterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’:
/usr/include/c++/7.3.0/debug/helper_functions.h:101:28:   required from ‘typename __gnu_debug::_Distance_traits<_Iterator>::__type __gnu_debug::__get_distance(const _Iterator&, const _Iterator&) [with _Iterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’
/usr/include/c++/7.3.0/debug/helper_functions.h:127:30:   required from ‘bool __gnu_debug::__valid_range_aux(const _InputIterator&, const _InputIterator&, typename __gnu_debug::_Distance_traits<_Iterator>::__type&, std::__false_type) [with _InputIterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’
/usr/include/c++/7.3.0/debug/helper_functions.h:156:31:   required from ‘bool __gnu_debug::__valid_range(const _InputIterator&, const _InputIterator&, typename __gnu_debug::_Distance_traits<_Iterator>::__type&) [with _InputIterator = tripoint_range::point_generator; typename __gnu_debug::_Distance_traits<_Iterator>::__type = std::pair<long int, __gnu_debug::_Distance_precision>]’
/usr/include/c++/7.3.0/debug/helper_functions.h:164:27:   required from ‘bool __gnu_debug::__valid_range(const _InputIterator&, const _InputIterator&) [with _InputIterator = tripoint_range::point_generator]’
/usr/include/c++/7.3.0/bits/stl_algo.h:746:7:   required from ‘_OIter std::copy_if(_IIter, _IIter, _OIter, _Predicate) [with _IIter = tripoint_range::point_generator; _OIter = std::back_insert_iterator<std::__debug::vector<tripoint> >; _Predicate = npc::move_away_from(const std::__debug::vector<sphere>&, bool)::<lambda(const tripoint&)>]’
src/npcmove.cpp:1809:7:   required from here
/usr/include/c++/7.3.0/debug/helper_functions.h:92:17: error: no match for ‘operator==’ (operand types are ‘const tripoint_range::point_generator’ and ‘const tripoint_range::point_generator’)
       if (__lhs == __rhs)
           ~~~~~~^~~~~~~~
```

### Steps to reproduce the behavior
make clean && make

### Misc info
a quick git bisect points towards c12dd939ff8cdb6229561bcd10f3a88ee78bb8f0 as the first bad commit

### PR DESCRIPTION
**Pull request by kevingranade**
This caused a build failure on my system because the debug version of std::copy_if() exercises the equality operator of its arguments.

This is technically required anyway since copy_if [requires](http://en.cppreference.com/w/cpp/algorithm/copy) its input iterators to meet the requirements of [InputIterator](http://en.cppreference.com/w/cpp/concept/InputIterator) , which in turn requires support for [EqualityComparable](http://en.cppreference.com/w/cpp/concept/EqualityComparable).

Fixes #23243

### CODE REVIEW

**Comment by illi-kun** [comment]
Jenkins rebuild

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

File: src/npcmove.cpp [hunk 1]
```diff
@@ -1804,15 +1804,15 @@ void npc::move_away_from( const std::vector<sphere> &spheres, bool no_bashing )
     std::vector<tripoint> escape_points;
 
     std::copy_if( range.begin(), range.end(), std::back_inserter( escape_points ),
-    [&]( const tripoint & elem ) {
```
Comment (ZhilkinSerg) [inline src/npcmove.cpp]: Changing of `npcmove.cpp` is not necessary as it brings astyle regression, otherwise looks good.

Comment (kevingranade) [reply src/npcmove.cpp]: ACK, my astyle version disagrees with the one on Jenkins, so it keeps telling me to change random things like this.

**Comment by ZhilkinSerg** [comment]
Wow. How did you made your changes without adding new commit?

**Comment by ZhilkinSerg** [comment]
Wow. How did you made your changes without adding new commit?

**Comment by Leland** [comment]
@ZhilkinSerg git rebasing, most likely.

**Comment by kevingranade** [comment]
@Leland has it, the easiest way is:
1. Have a commit.
2. Oops there's a problem, make local edits.
3. ```git add``` changes.
4. ```git commit --amend```
5. ```git push -f```
If the commit you want to change isn't the most recent one, you'll need to do a 'rebase' instead, that gets complicated so I won't go into detail here.

**Comment by ZhilkinSerg** [comment]
Thanks!
