### PR TITLE
Create template from already existing character

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Features "Create template from already existing character"```

#### Purpose of change
Kinda implements #33716 via character templates
Allows the creation of templates from existing world characters.

#### Describe the solution
Loads the world the selected character is in. Creates a template with the already existing ```sate_template()``` function. Modifies player id and mission status to prevent load errors.
These templates can not be modified (eg. Skills, Traits, Professions, etc)
Only things like Name, Gender, Starting location (Which are available on the last Character creation page. See image.)

### CODE REVIEW

File: src/avatar.h [hunk 1]
```diff
@@ -211,4 +215,95 @@ class avatar : public player
         int per_upgrade = 0;
 };
 
+struct points_left {
```
Comment (BevapDin) [inline src/avatar.h]: Does all of this have to be in the header? At least the functions calling `get_option` should be in the cpp file, so the header does not have to include "options.h".

File: src/avatar.h [hunk 2]
```diff
@@ -44,6 +45,7 @@ class avatar : public player
         bool create( character_type type, const std::string &tempname = "" );
         void randomize( bool random_scenario, points_left &points, bool play_now = false );
         bool load_template( const std::string &template_name, points_left &points );
+        static void save_template( const avatar &u, const std::string &name, const points_left &points );
```
Comment (BevapDin) [inline src/avatar.h]: Why is this a static function of `avatar`, taking an object of type `avatar` as parameter? Why not make it non-static and use the implicit `this` pointer:
```suggestion
        void save_template( const std::string &name, const points_left &points ) const;
```

**Comment by OzoneH3** [comment]
Travis complains but looks like an unrelated testcase failure.

**Comment by anothersimulacrum** [comment]
I can no longer compile on master due to 3ca8f49337fff75c7dcdf12ac7954a877f7607dc
```
/usr/bin/ld: obj/tiles/npc.o: in function `npc::randomize(string_id<npc_class> const&)':
/home/dev/git/cataclysm-dda/src/npc.cpp:312: undefined reference to `Character::setID(character_id)'
/usr/bin/ld: obj/tiles/savegame_json.o: in function `player::load(JsonObject&)':
/home/dev/git/cataclysm-dda/src/savegame_json.cpp:880: undefined reference to `Character::setID(character_id)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:768: cataclysm-tiles] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: ../cataclysm.a(npc.o): in function `npc::randomize(string_id<npc_class> const&)':
/home/dev/git/cataclysm-dda/src/npc.cpp:312: undefined reference to `Character::setID(character_id)'
/usr/bin/ld: ../cataclysm.a(savegame_json.o): in function `player::load(JsonObject&)':
/home/dev/git/cataclysm-dda/src/savegame_json.cpp:880: undefined reference to `Character::setID(character_id)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:35: cata_test] Error 1
make: *** [Makefile:1048: tests] Error 2
```
make command `make -j4 -s CCACHE=1 TILES=1 RELEASE=1 DEBUG_SYMBOLS=1`
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC)
```
