### PR TITLE
Fix build error on FreeBSD

### LINKED ISSUE #12414: Build failure on FreeBSD
In file included from src/veh_typedef.cpp:1:
In file included from src/veh_type.h:5:
src/int_id.h:92:20: error: implicit instantiation of undefined template 'std::__1::hash<int>'
            return hash<int>()( v.to_i() );
                   ^
/usr/include/c++/v1/memory:3062:29: note: template is declared here
template <class _Tp> struct hash;

Possibly introduced by commit 14b2e516755ca7a20b8a27a32c83215a7defff7b

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/15976862-build-failure-on-freebsd?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mugling**
Fixes #12414

### CODE REVIEW

**Comment by BevapDin** [comment]
Was my fault. The specialization of `std::hash` needs the functional header for the declaration of the template `std::hash<T>`.
