### ISSUE TITLE
Compilation error with VS2017

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#22542]
Game fails to compile with Visual Studio 2017 on Windows 10, with #22533 being the latest commit.
```
sdltiles.obj : error LNK2001: unresolved external symbol "struct cata_cursesport::WINDOW * w_hit_animation" (?w_
       hit_animation@@3PEAUWINDOW@cata_cursesport@@EA) [D:\Program Files Installess\Games\Roguelike\CataclysmDDA\cdda-p
       lay\msvc-full-features\Cataclysm.vcxproj]

```
[Full build log here](https://gist.github.com/Maddremor/74212f076b8a0a7a82ec3fba277223ea)
