### ISSUE TITLE
MinGW tiles build warnings

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22233]
Apparently MinGW in MSYS2 doesn't like `%ll` format arguments introduced in #22215.

EDIT: It may be related to 32-bit vs 64-bit builds. I got 64-bit build working, but the 32-bit one produces the errors below.
```
gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 7.2.0
```

```
In file included from src/string_formatter.h:7:0,
                 from src/ret_val.h:5,
                 from src/item.h:20,
                 from src/inventory.h:6,
                 from src/character.h:7,
                 from src/player.h:5,
                 from src/sdltiles.cpp:10:
src/compatibility.h: In function 'std::__cxx11::string to_string(long long int)':
src/compatibility.h:53:39: error: unknown conversion type character 'l' in format [-Werror=format=]
     snprintf( buffer, size, "%lld", n );
                                       ^
src/compatibility.h:53:39: error: too many arguments for format [-Werror=format-extra-args]
src/compatibility.h:53:39: error: unknown conversion type character 'l' in format [-Werror=format=]
src/compatibility.h:53:39: error: too many arguments for format [-Werror=format-extra-args]
src/compatibility.h: In function 'std::__cxx11::string to_string(long long unsigned int)':
src/compatibility.h:62:39: error: unknown conversion type character 'l' in format [-Werror=format=]
     snprintf( buffer, size, "%llu", n );
                                       ^
src/compatibility.h:62:39: error: too many arguments for format [-Werror=format-extra-args]
src/compatibility.h:62:39: error: unknown conversion type character 'l' in format [-Werror=format=]
src/compatibility.h:62:39: error: too many arguments for format [-Werror=format-extra-args]
```

**Comment by laeaton2001** [comment]
I also get a mass of errors trying to compile in visual studio now. The below 4 get repeated 105 odd times. I could compile fine before this so I don't think it's my setup.
![image](https://user-images.githubusercontent.com/32654313/31970881-f9a16f46-b95c-11e7-8e7e-959c365fc516.png)

**Comment by AlecWhite** [comment]
Can confirm on VIsual Studio.

`1>e:\mods and modding\cdda\source\cataclysm-dda\src\string_formatter.h(199): error C2059: syntax error: '('
1>e:\mods and modding\cdda\source\cataclysm-dda\src\string_formatter.h(199): error C2238: unexpected token(s) preceding ';'
1>e:\mods and modding\cdda\source\cataclysm-dda\src\string_formatter.h(201): error C2178: 'std::string' cannot be declared with 'mutable' specifier
1>e:\mods and modding\cdda\source\cataclysm-dda\src\string_formatter.h(201): error C2226: syntax error: unexpected type 'std::string'`

A bazillion errors out of string_formatter,h

**Comment by nshcat** [comment]
It seems like non-standard extensions were used in `string_formatter.h`?

**Comment by Robik81** [comment]
In VS, I managed to compile the thing after these changes:

string_formatter.h
replace 
__attribute__( ( noreturn ) )
with
__declspec(noreturn)

optional.h
replace
constexpr optional( const nullopt_t ) noexcept : optional() { }
with
constexpr optional( const nullopt_t ) noexcept : dummy(), full(false) { }

Now, I know very little about C++, except I hate it... game does run, but I am not sure what these changes broke.

**Comment by PapaPetro** [comment]
Related issue:
Experimental Builds for Windows Tiles web releases stopped producing.
http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/

Last build was 2017-10-21 7:21 AM.  Most likely coincides to #22215 being merged later that day at 2017-10-21 5:26 PM as mentioned by Coolthulhu.

**Comment by narc0tiq** [comment]
This may have been fixed by #22362? The Win32-Tiles build definitely was.

**Comment by illi-kun** [comment]
Assume this issue was fixed in the PR mentioned by narc above. Feel free to reopen if this assumption is incorrect.
