### ISSUE TITLE
Problem compiling with Visual Studio

### ISSUE THREAD

**Issue by AlecWhite** [CleverRaven/Cataclysm-DDA#21161]
Using Visual Studio 2015 on Windows 7 can't compile latest SDL tiles version.

Here is the log with /verbose (today I learn what that is)
[Cataclysm.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/1043248/Cataclysm.txt)

After spending all this day looking what the linker error were, and after manually checking commits(I discovered later that I could have used git bisect) I found out that this commit  https://github.com/CleverRaven/Cataclysm-DDA/commit/dbf94ea32432320fc874237d93965c069fb674f3 is the one causing the problem.

I would have spotted this problem earlier if I were more used to sync my local repo, sorry about that.

**Comment by AlecWhite** [comment]
It seems that @Graywolfe813 had the same problem with gnu stdc++ on android.

**Comment by Graywolfe813** [comment]
Worth noting that the issue on Android was due to the gnu std C++ library being deprecated, and thus neglected.

Microsoft isn't terribly good at keeping up with, or following, standards.  Could be related.

**Comment by Qrox** [comment]
I remember having a similar problem earlier with MinGW, and fixed it by doing a clean build. Not sure if this is the same problem though.

**Comment by AlecWhite** [comment]
>fixed it by doing a clean build.

Tried that but with no luck.

**Comment by AlecWhite** [comment]
>fixed it by doing a clean build.

Tried that but with no luck.

**Comment by kevingranade** [comment]
Odd, is it still complaining about the same thing now? I totally overhauled how string_id::NULL works, so I'd at least expect a different error.

**Comment by AlecWhite** [comment]
Now I get `error C2065: 'SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING': undeclared identifier`

Here's the /verbose log.
[Cataclysm.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/1046611/Cataclysm.txt)

Also just to be sure that I am doing it right. 
To update my local repo is `git pull upstream master`, when remote upstream is https://github.com/CleverRaven/Cataclysm-DDA right?

**Comment by Qrox** [comment]
> Now I get error C2065: 'SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING': undeclared identifier

Try updating SDL to 2.0.5. PR #21147 introduced this change.

**Comment by AlecWhite** [comment]
After more time than I'm willing to admit. I managed to update SDL, the bat, the SDL.h and the lib. 
Clean build and still have the same error. Here's the /verbose log.
[Cataclysm.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/1046778/Cataclysm.txt)

Should I make a PR regarding updating SDL for VS solution or will someone else do it or how does the whole updating a build for VS work?

**Comment by spacenookie** [comment]
build failure on ubuntu 14.04 (comes with libsdl2-2.0). updated to libsdl2-2.0.5 by compiling from source, which cleared the build failure but I now have problem with doubled key presses (press any key and game reacts as though you pressed it twice) which makes game unplayable

**Comment by Qrox** [comment]
I am informed that "clean" under VS only removes the build artifact. @AlecWhite Have you tried "rebuild" or manually removing the game binaries and object files then build again?

**Comment by AlecWhite** [comment]
Manually deleted the binaries/objs and rebuild and it is still giving the same error.

**Comment by kevingranade** [comment]
Looks like we need to back out the thread hint thing for the time.

**Comment by kolsurma** [comment]
The thread hint is a simple fix, download SDL 2.0.5, correct WINDEPEND.prop to the new folder.

The linker issue seems to be coming from `static const string_id<T> &NULL_ID();`, VS really seems to dislike this for some reason.

**Comment by AlecWhite** [comment]
@kevingranade I'm really sorry. By same error I meant the same linker error the thread hint was fixed once I updated SDL.

**Comment by AlecWhite** [comment]
@Rivet-the-Zombie why was this closed? the original linker error of this issue is still happening. 
The SDL error was introduced later and I should have opened a new issue regarding that particular one. But the introduced with https://github.com/CleverRaven/Cataclysm-DDA/commit/dbf94ea32432320fc874237d93965c069fb674f3 is still there.

**Comment by Qrox** [comment]
@AlecWhite it was automatically closed since #21168 references this as `Fixes #21161`.

**Comment by AlecWhite** [comment]
Didn't know github did such things.

**Comment by AlecWhite** [comment]
Did a `git bisect` and it told me.
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[dbf94ea32432320fc874237d93965c069fb674f3] Explicitly initialize string_id template instances to make clang happy.
Which makes sense with the ` 1>computer.obj : error LNK2001: unresolved external symbol "public: static class string_id<struct mtype> const string_id<struct mtype>::NULL_ID" (?NULL_ID@?$string_id@Umtype@@@@2V1@B)` errors as it seems all of them are string_id.

@kevingranade could you please explain me what did you do in that commit? 
By what I googled it seems the linker can't find the function, so it would in theory be fixed by including the .cpp right?

Also is worth commenting that I think I'm out of my depth for this one.

**Comment by ufft47** [comment]
about visual studio 2015: const string_id<type> &string_id<type>::NULL_ID() --Link Error lnk2001 unresolved external symbol and fix

`1>monstergenerator.obj : error LNK2001:unresolved external symbol "public: static class string_id<struct mtype> const & __cdecl string_id<struct mtype>::NULL_ID(void)" (?NULL_ID@?$string_id@Umtype@@@@SAAEBV1@XZ)`

----------------fix string_id_null_ids.cpp------------------------

#include "string_id.h"

// These are centralized in this file because they must appear in one and only one compilation unit,
// and it's problematic to define them in the respective cpp files for each class.
// Very repitious, so define them with a macro.
`#define MAKE_NULL_ID( type, ... ) \
class type; \
template<> const string_id<type> &string_id<type>::NULL_ID() { \
    static string_id<type> id = string_id<type>( __VA_ARGS__ ); \
    return id; \
}`

MAKE_NULL_ID( activity_type, "ACT_NULL", -1 );
MAKE_NULL_ID( harvest_list);
MAKE_NULL_ID( effect_type, "null");
//MAKE_NULL_ID( furn_t, "f_null", 0 );
MAKE_NULL_ID( material_type, "null", 0 );
//MAKE_NULL_ID( MonsterGroup, "GROUP_NULL" );
//MAKE_NULL_ID( mtype, "mon_null" );
//MAKE_NULL_ID( mutation_branch );
//MAKE_NULL_ID( oter_t, "", 0 );
//MAKE_NULL_ID( oter_type_t, "", 0 );
//MAKE_NULL_ID( requirement_data, "null" );
//MAKE_NULL_ID( species_type, "spec_null" );
//MAKE_NULL_ID( ter_t, "t_null", 0 );
//MAKE_NULL_ID( trap, "tr_null" );

MAKE_NULL_ID( overmap_special, "", 0 );
MAKE_NULL_ID( Skill, "none" );
//MAKE_NULL_ID( mission_type, "mission_type" );
MAKE_NULL_ID( npc_class, "NC_NONE" );
MAKE_NULL_ID( ammunition_type, "NULL" );
MAKE_NULL_ID( vpart_info, "null" );
MAKE_NULL_ID( emit, "null" );

//luke
`#define MAKE_NULL_ID2( type, ... ) \
struct type; \
template<> const string_id<type> &string_id<type>::NULL_ID() { \
    static string_id<type> id = string_id<type>( __VA_ARGS__ ); \
    return id; \
}`

MAKE_NULL_ID2(mtype, "mon_null");
MAKE_NULL_ID2(oter_t, "", 0);
MAKE_NULL_ID2(oter_type_t, "", 0);
MAKE_NULL_ID2(ter_t, "t_null", 0);
MAKE_NULL_ID2(trap, "tr_null");
MAKE_NULL_ID2(furn_t, "f_null", 0);
MAKE_NULL_ID2(MonsterGroup, "GROUP_NULL");
MAKE_NULL_ID2(mission_type, "mission_type");
MAKE_NULL_ID2(species_type, "spec_null");
MAKE_NULL_ID2(mutation_branch);
MAKE_NULL_ID2(requirement_data, "null");

**Comment by Qrox** [comment]
@ufft47 Would you consider creating a PR for the fix?

**Comment by AlecWhite** [comment]
@ufft47 does that fix all the others symbol problems too?
