### ISSUE TITLE
0.F (curses) doesn't work on mac: chkstk_darwin libSystem.B.dylib error

### ISSUE THREAD

**Issue by PLUUZ** [CleverRaven/Cataclysm-DDA#49572]
**Describe the bug**
Double clicking on mac curses app (cdda-osx-curses-x64-2021-07-03-0512) doesn't launch the game. Instead the terminal shows this message:
```
export PATH=/usr/bin:/bin:/usr/sbin:/sbin DYLD_LIBRARY_PATH=. DYLD_FRAMEWORK_PATH=.; cd '/Applications/Games/Cataclysm.app/Contents/Resources' && ./cataclysm; exit
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Games/Cataclysm.app/Contents/Resources/./cataclysm
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Games/Cataclysm.app/Contents/Resources/./cataclysm
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
logout
```

**Steps To Reproduce**
    Double click on Cataclysm.app

**Expected behavior**
The game starts.

**Versions and configuration**
OS: Mac OS 10.11.6
Graphics version: Curses
game version: 0.F cdda-osx-curses-x64-2021-07-03-0512

**Comment by actual-nh** [comment]
I get the same on 10.12.6. (How do I get it to use the included libintl.8.dylib, BTW? I'm used to compiling it myself... the command line won't run because it isn't including that.)

**Comment by actual-nh** [comment]
DYLD_LIBRARY_PATH=. enables it to use the included libintl.8.dylib, now getting the same result as above.

**Comment by actual-nh** [comment]
From <https://github.com/esy/esy/issues/1169>, <https://stackoverflow.com/questions/63221290/how-to-resolve-missing-symbol-chkstd-darwin-in-libsystem-b-dylib-osx>, and others, looks like it's that OSX_MIN of 10.15 won't run on anything prior to 10.14; I don't know how far back one targeted at 10.13 will run on. @BrettDong, IIRC you've got access to some machines you could try compiling for different OSX versions? I can test for 10.12.6 running.

**Comment by actual-nh** [comment]
Confirmed that local curses build with RELEASE=1 but OSX_MIN=10.12 works fine.

**Comment by BrettDong** [comment]
Lowering `OSX_MIN` would solve the issue but I don't recommend to have it lower than 10.12, because the system library shipped prior to Mac OS X 10.12 has incomplete and probably incompatible C++14 support, where program compiled with `-std=c++14` can sometimes have bizarre behaviours from my experience in other projects.

**Comment by actual-nh** [comment]
Should 2 versions be available, 10.12 and 10.15+?

**Comment by BrettDong** [comment]
> Should 2 versions be available, 10.12 and 10.15+?

10.12+ should be enough.

**Comment by actual-nh** [comment]
There appear to be some further difficulties with the tiles version - see #49570. Some library symlinks help but are not sufficient.

**Comment by PLUUZ** [comment]
Hello, from what I've read in this and other mac issue threads, I see that 10.11 support isn't practical.  However, if the new plan is to support 10.12 and later, is there going to be a rebuild of 0.F Mac to put on the releases page, which fixes the various issues that make 0.F problematic on a lot of mac systems? Since the developers have warned that unstable releases are going to be quite unstable for the time being, it might be nice to do this so Mac players have a working version of latest stable release to use.

**Comment by actual-nh** [comment]
> edit: i just saw the "backport" tag and looked up the definition of that word... so yes it seems like there is already a plan to do this.

Another bug is making a 0.F-1 bugfix release very likely to be soon - font problems on some machines (Mac and Windows) resulting in blanks where text should be...

**Comment by BrettDong** [comment]
> Another bug is making a 0.F-1 bugfix release very likely to be soon - font problems on some machines (Mac and Windows) resulting in blanks where text should be...

This could be fixed by replacing Terminus.ttf in the repo with a Mac compatible one, for instance the one tested in #50149.

**Comment by actual-nh** [comment]
> > Another bug is making a 0.F-1 bugfix release very likely to be soon - font problems on some machines (Mac and Windows) resulting in blanks where text should be...
> 
> This could be fixed by replacing Terminus.ttf in the repo with a Mac compatible one, for instance the one tested in #50149.

What about the Windows cases?

**Comment by PLUUZ** [comment]
Just to note, 0.F-1 curses does work on OSX 10.11.6 for whatever reason, despite osx 10.12 being chosen as the target minimum version.

**Comment by anothersimulacrum** [comment]
0.G is out, I expect this won't be fixed.
