### ISSUE TITLE
Build error on clang 9.0.0 (OS X)

### ISSUE THREAD

**Issue by sxmichaels** [CleverRaven/Cataclysm-DDA#22562]
Game version: `c96024cb57`

Operating system: OS X 10.12.6

Tiles or curses: Tiles

Mods active: N/A

### Expected behavior
Building an unmodified copy of CDDA should work.

### Actual behavior
I get the following error:
```
src/game.h:1073:51: error: implicit instantiation of undefined template 'std::__1::array<float, 21>'
        mutable std::array<float, OVERMAP_LAYERS> latest_lightlevels;
                                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:222:64: note:
      template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
In file included from src/activity_item_handling.cpp:3:
src/game.h:1073:51: error: implicit instantiation of undefined template 'std::__1::array<float, 21>'
        mutable std::array<float, OVERMAP_LAYERS> latest_lightlevels;
                                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:222:64: note:
      template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
```

### Steps to reproduce the behavior
Build with clang 9.0.0 (may need to do so on OS X specifically)

**Comment by Leland** [comment]
Yeah, I updated to High Sierra and all kinds of hijinks are occurring now
