### PR TITLE
Fix unused variables on macOS

### PR DESCRIPTION
**Pull request by shazow**
Build error introduced in #22176.

Error that this fixes on macOS using clang:

```
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DOSX_SDL2_LIBS -DTILES -DUSE_HOME_DIR -ffast-math -Os  -Wall -Wextra    -fsigned-char -stdlib=libc++ -Werror -std=c++11 -MMD -MP -mmacosx-version-min=10.7 -D_THREAD_SAFE -I/usr/local/include/SDL2 -DSDL_SOUND -I/usr/local/include/SDL2 -D_THREAD_SAFE -I/usr/local/include -c src/translations.cpp -o obj/tiles/translations.o
src/translations.cpp:175:42: error: unused parameter 'lang' [-Werror,-Wunused-parameter]
bool isValidLanguage( const std::string &lang )
                                         ^
src/translations.cpp:180:41: error: unused parameter 'lcid' [-Werror,-Wunused-parameter]
std::string getLangFromLCID( const int &lcid )
                                        ^
2 errors generated.
make: *** [obj/tiles/translations.o] Error 1
```

### CODE REVIEW

**Comment by BevapDin** [comment]
Or you could simply comment out the parameter name in the parameter list, e.g.

`foo( std::string /*lang*/ ) { ... }`.

It's a bit less cryptic then the cast to `void`.

**Comment by shazow** [comment]
@BevapDin Sounds good, I'll force-push a change shortly. I went with the void casting because that's what I saw other examples in the codebase do and I wanted to stay consistent:

```
src/animation.cpp
413:    (void)i;          //unused
414:    (void)trajectory; //unused
580:    (void)p; //unused

src/construction.cpp
891:    ( void )p; //unused

src/iexamine.cpp
80:    (void)p; //unused
642:    (void)p; //unused

src/translations.cpp
177:    (void)lang; //unused
183:    (void)lcid; //unused

src/iuse.cpp
211:    (void)p; //unused

src/mondeath.cpp
648:    (void)z; //unused

src/npctalk.cpp
3181:    ( void )p; //unused
```

**Comment by shazow** [comment]
Pushed the changes, please take a look.
