### ISSUE TITLE
Build error: src/ranged.h:51:37: error: ‘spell’ has not been declared

### ISSUE THREAD

**Issue by tuxayo** [CleverRaven/Cataclysm-DDA#79363]
### Describe the bug

```
[....]
g++ -Isrc -isystem src/third-party -DRELEASE -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -DIMTUI -DPREFIX="/usr" -DDATA_DIR_PREFIX -DUSE_XDG_DIR -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -Wno-error=maybe-uninitialized -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -Wredundant-decls -g1 -fsigned-char -std=c++17 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MMD -MP  -c src/ranged.cpp -o obj/ranged.o
In file included from src/ranged.cpp:1:
src/ranged.h:51:37: error: ‘spell’ has not been declared
   51 | trajectory mode_spell( avatar &you, spell &casting, bool no_fail, bool no_mana );
      |                                     ^~~~~
g++ -Isrc -isystem src/third-party -DRELEASE -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -DIMTUI -DPREFIX="/usr" -DDATA_DIR_PREFIX -DUSE_XDG_DIR -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -Wno-error=maybe-uninitialized -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -Wredundant-decls -g1 -fsigned-char -std=c++17 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MMD -MP  -c src/recipe.cpp -o obj/recipe.o
g++ -Isrc -isystem src/third-party -DRELEASE -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -DIMTUI -DPREFIX="/usr" -DDATA_DIR_PREFIX -DUSE_XDG_DIR -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -Wno-error=maybe-uninitialized -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -Wredundant-decls -g1 -fsigned-char -std=c++17 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MMD -MP  -c src/recipe_dictionary.cpp -o obj/recipe_dictionary.o
g++ -Isrc -isystem src/third-party -DRELEASE -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -DIMTUI -DPREFIX="/usr" -DDATA_DIR_PREFIX -DUSE_XDG_DIR -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -Wno-error=maybe-uninitialized -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -Wredundant-decls -g1 -fsigned-char -std=c++17 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MMD -MP  -c src/recipe_groups.cpp -o obj/recipe_groups.o
src/ranged.cpp:545:22: error: ‘target_handler::trajectory target_handler::mode_spell(avatar&, spell&, bool, bool)’ should have been declared inside ‘target_handler’
  545 |         bool no_mana )
      |                      ^
src/ranged.cpp:544:28: error: no previous declaration for ‘target_handler::trajectory target_handler::mode_spell(avatar&, spell&, bool, bool)’ [-Werror=missing-declarations]
  544 | target_handler::trajectory target_handler::mode_spell( avatar &you, spell &casting, bool no_fail,
      |                            ^~~~~~~~~~~~~~
g++ -Isrc -isystem src/third-party -DRELEASE -DBACKTRACE -DLIBBACKTRACE -DLOCALIZE -DIMTUI -DPREFIX="/usr" -DDATA_DIR_PREFIX -DUSE_XDG_DIR -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -Wno-error=maybe-uninitialized -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -Wredundant-decls -g1 -fsigned-char -std=c++17 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MMD -MP  -c src/relic.cpp -o obj/relic.o
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
make: *** [Makefile:1103: obj/ranged.o] Error 1
make: *** Waiting for unfinished jobs....

```

### Attach save file

N/A

### Steps to reproduce

1. Build with GCC 14.2 (guess on why it's happening)

### Expected behavior

Build should work on latest stable GCC

### Versions and configuration

- EndeavourOS (Arch Linux based)
- game version: aea8979

**Comment by tuxayo** [comment]
Or maybe it's my global compile flags?
```
CFLAGS="-march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

```

**Comment by tuxayo** [comment]
I suspect that I messed up updating my source directory when I last built it more than a year ago.
So I might have old files lying around!
Because now it can build past ranged.cpp without having that error.

Sorry for the false positive.
