### PR TITLE
Fix incorrect migration

### LINKED ISSUE #72583: [Experimental] some "Rural Roads" replaced with "% nether-chewed field"
### Describe the bug

Updated the game and reloaded my save. Noticed some rural roads near rural houses have been replaced with an % called "nether-chewed field" after an error related to "rural roads". 

### Attach save file

N/A

### Steps to reproduce

Use 4 or 5 day old build.

Start a new game with a new character.

Reveal Map and ensure you have a few good amount of rural roads and rural houses within sight. (Teleport to several of them so they register in your map memory too I guess?)

Save and Quit. 

Update to "experimental build 2024-03-24-0121" 

Reload the game

Enjoy the several error screens related to rural roads before you can get into the world. 

Open map and observe the rural roads and spot "%"s near them. 

### Expected behavior

Random Nether Terrain should not replace existing terrain. 

### Screenshots

image

### Versions and configuration

Linux 

Experimental Build cf9267f
(Refer to Screenshot)

### Additional context

///I didn't test this but I wouldn't be surprised if even generating a new playthrough using the specified build would already lead to this by default. //// 

Just did the above out of sheer curiosity and it seems the bug only occurs with saves from different builds and only with specific rural roads.

Having random black spots of terrain is an eyesore tbh.

### PR DESCRIPTION
**Pull request by hexagonrecursion**
#### Summary

None

#### Purpose of change

Fixes #72583

#72431 removed some oter_id's, but made a couple of mistakes when writing a migration

#### Describe the solution

1. "**dirt_road_forest**_3way_north" and 3 other rotations never existed (verified via git log -S) - I replaced it with the correct id - "**dirt_road_3way**_forest_north" - 3way before forest instead of after it
2. It looks like the map I was testing this with generated "cabin_liam_driveway_**north**" rather than "cabin_liam_driveway" - I kept "cabin_liam_driveway" migration just in case. Note: we don't need migrations for "cabin_liam_driveway_**west**" and 2 other rotations because cabin_liam has "rotate": false

#### Testing

Loaded my save - no more errors from overmap::unserialize(const JsonObject&)] Loaded invalid oter_id

#### Additional context

I am still getting this error in my save:
```
ERROR : src/generic_factory.h:513 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = oter_t]] invalid overmap terrain id "dirt_road_3way_east"
```
The log **does** contain messages about successful migrations from dirt_road_3way_east to rural_road_nsw.
It appears something in C++ might be trying to read a save file **before it is migrated** - out of scope for this PR - will debug and report separately

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
CI failed - unrelated build error: "no matching function for call to 'write_var_value'". Did someone check in **and merge** code that fails to build?

**Comment by perryprog** [comment]
It was two PRs being merged at once that didn't account for each other, it's fixed on master now if you want to rebase.

**Comment by Procyonae** [comment]
Whoops sorry I meant to double check those before I put the PR up, writing the migration was really messing with my head

**Comment by hexagonrecursion** [comment]
Can't run tests:
> item homeopathic_pills could not be put in container pillbox when spawning item group pillbox_used: not enough space.  This can be resolved either by changing the container or contents to ensure that they fit, or by specifying an overflow behaviour via "on_overflow" on the item group.
> item antifungal could not be put in container pillbox when spawning item group pillbox_used: not enough space.  This can be resolved either by changing the container or contents to ensure that they fit, or by specifying an overflow behaviour via "on_overflow" on the item group.

possibly broken by #72261
