### ISSUE TITLE
Android builds are failing again

### ISSUE THREAD

**Issue by HeShallNot** [CleverRaven/Cataclysm-DDA#31095]
# Describe the bug

Android builds are failing again. I think this was introduced by #31047 which adds diagonal modifiers. I might be mistaken though.

Here's the log from Jenkins

> 10:53:46   /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/sdltiles.cpp:1533:20: error: use of undeclared identifier 'handle_arrow_combo'
10:53:46               return handle_arrow_combo( keysym.sym );
10:53:46                      ^
10:53:46   /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/sdltiles.cpp:1535:13: error: use of undeclared identifier 'end_arrow_combo'
10:53:46               end_arrow_combo();
10:53:46               ^
10:53:46   2 errors generated.
10:53:46   make: *** [/var/lib/jenkins/workspace/Cataclysm-Android/android/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/main/sdltiles.o] Error 1
10:53:46   make: *** Waiting for unfinished jobs....
10:53:46 
10:53:46 
10:53:46 * Try:
10:53:46 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
10:53:46 
10:53:46 * Get more help at https://help.gradle.org
10:53:46 
10:53:46 BUILD FAILED in 49m 58s
10:53:46 19 actionable tasks: 19 executed
10:53:48 Build step 'Invoke Gradle script' changed build result to FAILURE
10:53:48 Build step 'Invoke Gradle script' marked build as failure
10:53:48 SSH: Current build result is [FAILURE], not going to run.
10:53:48 Recording fingerprints
10:53:49 Finished: FAILURE

# Additional context

Sorry for always nagging about android builds, currently it's the only platform where i could play :)

Edit: Sorry I didn't notice this pr #31074 sooner. Closing now.
