### PR TITLE
Fix compiling error introduced in #31789

### PR DESCRIPTION
**Pull request by Maddremor**
#### Summary
```SUMMARY: Bugfixes "Fix compiling error introduced in #31789"```

#### Purpose of change
Got compiling errors ```magic_teleporter_list.cpp:(.text+0x1ff5): undefined reference to `avatar* game::critter_at<avatar>(tripoint const&, bool)'``` after #31789 got merged.

#### Describe the solution
ifreund told me to add a line. Said line worked.

#### Describe alternatives you've considered
Waiting for someone else to get the same issue and fix it.

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/insert-tire-here-runs-over-something-xevery-wheel/20556/10

**Comment by KorGgenT** [comment]
Thanks a bunch for fixing this, sorry i didn't notice it when compiling myself.
